[package]
name = "impl_algorithm_for_data_structure"
version = "0.1.0"
authors = ["Yifan Pan <4anpan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
